config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'venues#index'

  devise_for :consumers, controllers: { registrations: 'consumers/registrations', omniauth_callbacks: 'omniauth_callbacks', invitations: 'users/invitations' }

  resources :venues, only: [:show, :update, :index, :create]
  resources :transactions, only: [:new, :create, :index]
  resources :bookings, only: [:new] do
    post :confirm, on: :collection
  end
  resource :cart, only: [:show]
  resource :balance, only: [:create] do
    get :show, as: :gifts
  end
  resources :reviews, only: [:new, :create, :index]
  resources :vouchers, only: [:update] do
    get :add_gift, on: :collection
  end
  get 'gift_card', to: 'vouchers#buy_gift_card', as: :buy_gift_card

  scope '/pro' do
    devise_for :pros, controllers: { invitations: 'users/invitations' }

    resources :pros
    resources :treatments do
      post :select_featured, on: :collection
    end
    resources :treatment_groups
    resources :daily_schedules, only: [:index, :destroy] do
      post :set, on: :collection
    end

    resources :teams, only: [:create, :show] do
      post :add_member, on: :member
      get :check_for_team, on: :collection
    end
    resources :bookings, only: [:create, :index, :destroy] do
      get :calendar, on: :collection
      post :mark_as_unavailable, on: :collection
      post :complete, on: :member
    end
    resources :venues, only: [:edit, :new]
    resources :bank_accounts, only: [:update, :edit, :new, :create]
    resource :dashboard, only: [:show]
  end

end

app/models/treatment.rb
# == Schema Information
#
# Table name: treatments
#
#  id                 :integer          not null, primary key
#  title              :string
#  description        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  pro_id             :integer
#  sale_price         :integer
#  price              :integer
#  duration           :string
#  treatment_type     :string
#  treatment_group_id :integer
#  featured           :boolean          default("false")
#

class Treatment < ActiveRecord::Base
  belongs_to :pro
  belongs_to :treatment_group

  has_many :bookings, dependent: :destroy

  validates_presence_of :pro_id
  validates_presence_of :title
  validates_presence_of :treatment_group_id
  validates_presence_of :sale_price
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_treatment, only: [:edit, :destroy, :update, :select_featured]

  def index
    @groups = TreatmentGroup.where(pro: current_user) - treatments_with_groups.keys
    @treatments_with_groups
  end

  def new
    authorize Treatment
    @group_id = params[:group_id]
    @treatment = Treatment.new
  end

  def edit
    authorize @treatment
  end

  def create
    @treatment = Treatment.new(treatment_params.merge(pro: current_user))
    authorize @treatment
    if @treatment.save
      redirect_to treatments_path, notice: 'Treatment Created'
    else
      redirect_to :back, notice: @treatment.errors.full_messages.join(', ')
    end
  end

  def update
    authorize @treatment
    if @treatment.update(update_params)
      redirect_to treatments_path, notice: 'Treatment Updated'
    else
      redirect_to :back, notice: @treatment.errors.full_messages.join(', ')
    end
  end

  def destroy
    authorize @treatment
    @treatment.destroy
    redirect_to treatments_path, notice: 'Treatment was deleted'
  end

  def select_featured
    redirect_to treatments_path, notice: '3 featured treatments max, you need to undo selection first' and return unless featured_selection_allowed?
    redirect_to treatments_path, notice: 'impossible to mark as featured' and return unless params[:featured]

    case params[:featured]
    when 'true'
      @treatment.update(featured: true)
      redirect_to treatments_path, notice: 'treatment is now featured'
    when 'false'
      @treatment.update(featured: false)
      redirect_to treatments_path, notice: 'treatment is now not featured'
    end
  end

  private

  def featured_selection_allowed?
    (current_user.treatments.where(featured: true).count < 3) || params[:featured] == 'false'
  end

  def treatments_with_groups
    @treatments_with_groups ||= Treatment.order(:title).where(pro: current_user).group_by(&:treatment_group)
  end

  def set_treatment
    @treatment = Treatment.find(params[:id])
  end

  def treatment_params
    params.require(:treatment).permit(:title, :treatment_type, :description, :sale_price, :price, :duration, :treatment_group_id)
  end

  def update_params
    params.require(:treatment).permit(:title, :treatment_type, :description, :sale_price, :price, :duration)
  end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/_treatment.html.erb
<div class='container'>
  <div class='row'>
    <div class='text-center'>
      <h3> Treatment details</h3> 
    </div>
    <div class='col-lg-6 col-lg-offset-3'>
      <%= simple_form_for(@treatment, html: {class: 'form-horizontal', id: 'contact-form'}) do |f| %>
      <%= f.error_notification %>
        <div class='form-group form-horizontal'>
          <%= f.input :title, required: false, autofocus: true, label: 'Title', input_html: { class: 'form-control'} %>
        </div>
        <div class='form-group'>
          <%= f.input :price, required: false, autofocus: false, label: fa_icon('gbp', text: 'Price,', right: true), input_html: { class: 'form-control'} %>
        </div>
        <div class='form-group'>
          <%= f.input :sale_price, required: false, autofocus: false, label: fa_icon('gbp', text: 'Sale Price,', right: true), input_html: { class: 'form-control'} %>
        </div>
        <div class='form-group'>
          <%= f.input :duration, collection: ApplicationHelper::DURATIONS.sort.map {|k,v| [v,k]}, required: false, autofocus: false, label: 'Duration', input_html: { class: 'form-control'} %>
        </div>
        <div class='form-group'>
          <%= f.input :treatment_type, collection: ApplicationHelper::TREATTYPE, required: false, autofocus: false, label: 'Treatment type', input_html: { class: 'form-control'} %>
        </div>            
        <div class='form-group'>
          <%= f.input :description, required: false, autofocus: false, label: 'Description', input_html: { class: 'form-control'} %>
        </div>  
        <div class='form-group'>
          <%= f.hidden_field :treatment_group_id, value: @group_id %>
          <%= f.button :submit, 'Save', class: 'btn btn-warning col-sm-12 last_div' %>
        </div>              
      <% end %>
    </div>
  </div>
</div>

app/views/treatments/edit.html.erb
<%= render 'treatment' %>

app/views/treatments/index.html.erb
<div class='container'>
  <div class='row col-lg-10 col-lg-offset-1'>
    <div class='button_down'>
      <% if @groups %>
        <% @groups.each do |group| %>
        <div class='form-group button-right col-md-12'><%= button_to "add treatment to new group #{group.name}", new_treatment_path, method: 'get', class: 'btn btn-success btn-sm', params: {group_id: group.id} %></div>
        <%end%>
      <%end%>      
    </div>
    <% unless @treatments_with_groups.blank? %>
      <% @treatments_with_groups.each_pair do |treatment_group, treatments| %>
        <div class='col-md-12 button_down'>
          <h4 class='col-md-10'>
            <%= link_to "#{treatment_group.name}", edit_treatment_group_path(treatment_group) %>
            <%= link_to(fa_icon('trash-o'), treatment_group_path(treatment_group), method: :delete) %>
          </h4>
          <div class='button-right'><%= button_to 'add treatment', new_treatment_path, method: 'get', class: 'btn btn-xs btn-xs-default', params: {group_id: treatment_group.id} %></div>
        </div>
        <table class='table table-striped treatments'>
          <tbody>
            <% treatments.each do |treatment| %>
              <tr>
                <td><%= link_to "#{treatment.title}", edit_treatment_path(treatment) %></td>
                <td><%= ::ApplicationHelper::DURATIONS[treatment.duration.to_i] %></td>
                <td>
                  <span class='line-through'><%= "#{treatment.price}" %><%= fa_icon('gbp') %></span>
                  <span class='red'><%= "#{treatment.sale_price}" %><%= fa_icon('gbp') %></span>
                </td>
                <td>
                  <% if treatment.featured %>
                    <%= fa_icon('check-square-o', text:"featured") %><br />
                    <%= link_to(fa_icon('undo', text: 'undo'), select_featured_treatments_path(id: treatment, featured: false), method: :post) %>
                  <% else %>
                    <%= fa_icon('square-o', text:"not featured") %><br />
                    <%= link_to('mark as featured', select_featured_treatments_path(id: treatment, featured: true), method: :post) %>
                  <% end %>
                </td>
                <td class='last'><%= link_to(fa_icon('trash-o'), treatment_path(treatment), method: :delete) %></td>
              </tr>
            <%end%>
          </tbody>
        </table>
      <%end%>
    <%end%>
    <%= simple_form_for(TreatmentGroup.new, html: {class: ''}) do |f| %>
    <%= f.error_notification %>
      <div class='input-group last_div button_down'>
        <%= f.input :name, required: false, autofocus: false, label: false, placeholder: 'enter group name', input_html: { class: 'form-control'} %>
      <span class='input-group-btn'>
        <%= f.button :submit, 'add new group', class: 'btn btn-warning last_div' %>
      </span> 
      </div>
    <% end %>
  </div>
</div>

app/views/treatments/new.html.erb
<%= render 'treatment' %>