config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'venues#index'

  devise_for :consumers, controllers: { registrations: 'consumers/registrations', omniauth_callbacks: 'omniauth_callbacks', invitations: 'users/invitations' }

  resources :venues, only: [:show, :update, :index, :create]
  resources :transactions, only: [:new, :create, :index]
  resources :bookings, only: [:new] do
    post :confirm, on: :collection
  end
  resource :cart, only: [:show]
  resource :balance, only: [:create] do
    get :show, as: :gifts
  end
  resources :reviews, only: [:new, :create, :index]
  resources :vouchers, only: [:update] do
    get :add_gift, on: :collection
  end
  get 'gift_card', to: 'vouchers#buy_gift_card', as: :buy_gift_card

  scope '/pro' do
    devise_for :pros, controllers: { invitations: 'users/invitations' }

    resources :pros
    resources :treatments do
      post :select_featured, on: :collection
    end
    resources :treatment_groups
    resources :daily_schedules, only: [:index, :destroy] do
      post :set, on: :collection
    end

    resources :teams, only: [:create, :show] do
      post :add_member, on: :member
      get :check_for_team, on: :collection
    end
    resources :bookings, only: [:create, :index, :destroy] do
      get :calendar, on: :collection
      post :mark_as_unavailable, on: :collection
      post :complete, on: :member
    end
    resources :venues, only: [:edit, :new]
    resources :bank_accounts, only: [:update, :edit, :new, :create]
    resource :dashboard, only: [:show]
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    cart_ids = ShoppingCart.new(current_user).cart_ids
    @cart_bookings = Booking.find(cart_ids)
    @cart_total = @cart_bookings.sum(&:sum)

    @subtotal = diff > 0 ? diff.to_i : 0
  end

  private

  def diff
    @gift_balance ||= current_user.balance&.amount ? current_user.balance.amount : 0
    @total_minus_balance ||= @cart_total - @gift_balance
  end
end

app/views/carts/show.html.erb
<div class='container'>

  <div class='row' >
    <div id='mycart' class='col-md-12'>
      <div class='margin_down margin_up'>
        <h4>My Cart</h4>
        <p> You've selected <span class='cart-count'><%= shopping_cart_count %></span> treatments!</p>
      </div>
      <% @cart_bookings.each do |booking|%>
        <div class='cart-booking col-md-8 col-sm-8'>
            <p class='col-md-6 col-sm-6'><%= booking.treatment.title %></p>
            <p class='col-md-4 col-sm-4'><%= booking.start_at.strftime("%B %d at %H:%M") %></p>
            <p class='col-md-2 col-sm-2'><%= ::ApplicationHelper::DURATIONS[booking.treatment.duration.to_i] %> needed</p>
            <%=link_to booking_path(booking), method: :delete  do%>
              <i class='fa fa-times' aria-hidden='true'></i>
            <%end%>
        </div>
      <%end%>
    </div>
  </div>
  .
  <div class='col-md-12'>
    <p><%= link_to(fa_icon('search', text: 'Find more treatments'), root_path) %></p>
    <%= form_tag confirm_bookings_path, class: 'col-md-6 button_down margin_up' do%>
      <%= hidden_field_tag :total, "#{@cart_total}" %>
      <span class='cart-radio'><%= radio_button_tag(:payment, 'yes') %>
      <%= label_tag(:paid, 'Pay now with card or PayPal') %></span>
      <span class='cart-radio'><%= radio_button_tag(:payment, 'no') %>
      <%= label_tag(:not_paid, 'Pay later at venue') %></span>

      <div class='margin_up'>
        <span class='cart-radio'><%= radio_button_tag(:payment, 'half') %>
        <%= label_tag(:use_gifts, 'Use gift balance') %></span>
        <span>Available Balance   <%= fa_icon('gbp', text: "#{current_user.balance&.amount.to_i}") %></span>
        <span class='form-group'>
          <%= text_field_tag :gifts_amount, params[:gifts_amount], placeholder: 'Enter amount', class: 'form-control' %>
        </span>
      </div>  

      <h5 class='margin_up'>Order total <span><%= fa_icon('gbp', text:"  #{@cart_total}") %></span></h5>
      <h5>Total to pay <span><%= fa_icon('gbp', text:"  #{@subtotal}") %></span></h5>

      <button class='btn btn-warning btn-md col-md-12'>
        <span class=>Checkout Now </span>
      </button>
    <%end%>
  </div>

</div>