config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'venues#index'

  devise_for :consumers, controllers: { registrations: 'consumers/registrations', omniauth_callbacks: 'omniauth_callbacks', invitations: 'users/invitations' }

  resources :venues, only: [:show, :update, :index, :create]
  resources :transactions, only: [:new, :create, :index]
  resources :bookings, only: [:new] do
    post :confirm, on: :collection
  end
  resource :cart, only: [:show]
  resource :balance, only: [:create] do
    get :show, as: :gifts
  end
  resources :reviews, only: [:new, :create, :index]
  resources :vouchers, only: [:update] do
    get :add_gift, on: :collection
  end
  get 'gift_card', to: 'vouchers#buy_gift_card', as: :buy_gift_card

  scope '/pro' do
    devise_for :pros, controllers: { invitations: 'users/invitations' }

    resources :pros
    resources :treatments do
      post :select_featured, on: :collection
    end
    resources :treatment_groups
    resources :daily_schedules, only: [:index, :destroy] do
      post :set, on: :collection
    end

    resources :teams, only: [:create, :show] do
      post :add_member, on: :member
      get :check_for_team, on: :collection
    end
    resources :bookings, only: [:create, :index, :destroy] do
      get :calendar, on: :collection
      post :mark_as_unavailable, on: :collection
      post :complete, on: :member
    end
    resources :venues, only: [:edit, :new]
    resources :bank_accounts, only: [:update, :edit, :new, :create]
    resource :dashboard, only: [:show]
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pending_bookings
  before_action :set_venue

  def show
    @impressionist_count = @venue ? @venue.impressionist_count(start_date: Time.now.beginning_of_month) : 0
  end

  private

  def set_venue
    @venue = current_user.venue
  end

  def set_pending_bookings
    arel = Booking.arel_table

    @bookings ||= current_user
                  .bookings
                  .where(confirmed: true, completed: false)
                  .order(:start_at)
                  .where(arel[:start_at]
                  .gteq(Time.zone.now))
  end
end

app/views/dashboards/show.html.erb
<div class='container-fluid'>
  <div class='row' >
    <div class="col-sm-4 col-md-3 button_down dashboard_sidebar">
      <div class='venue_show_img'><%= venue_image(@venue) if @venue %></div>
      <div class="col-sm-12 col-md-12 margin_up"><%= rating_stars(@venue) if @venue %></div>
      <%= link_to(fa_icon('pencil', text: 'Edit venue details'), check_venue_path, class: 'col-sm-12 col-md-12 button_down') %>
      <% if @venue %>
        <%= link_to(fa_icon('eye', text: 'Preview on SpecialEyes'), venue_path(@venue), class: 'col-sm-12 col-md-12 margin_up') %>
        <%= form_tag new_pro_invitation_path, method: :get, class: 'col-md-6 button_down margin_up' do%>
          <button class='btn btn-default'>
            Request more ratings
          </button>
        <%end%>
       <% end %> 
      <%= link_to 'Help', root_path, class: 'col-sm-12 col-md-12 down_section' %>
      <div class="col-sm-12 col-md-12 margin_up"><%= mail_to 'support@specialeyes.london' %></div>
      <%= link_to 'Live Chat', root_path, class: 'col-sm-12 col-md-12 margin_up' %>
    </div>

    <div class="col-sm-8 col-md-9 margin_up">
      <h2>Dashboard</h2>

      <div class="col-sm-12 col-md-12 margin_up">
        <div class="col-sm-4 col-md-4 dashboard_icon">
          <%= fa_icon('check-square-o') %>
          <p><%= current_user.booking_this_month %></p>
          <h5>bookings this month</h5>
        </div>
        <div class="col-sm-4 col-md-4 dashboard_icon">
          <%= fa_icon('group') %>
          <p><%= @impressionist_count %></p>
          <h5>page visit this month</h5>
        </div>      
        <div class="col-sm-4 col-md-4 dashboard_icon">
          <%= fa_icon('thumbs-o-up') %>
          <p><%= current_user.profile_score %></p>
          <h5>profile score</h5>
        </div>      
      </div>

      <div class="table-responsive col-sm-12 col-md-12 margin_up">
        <h4>Pending bookings</h4>
        <%= link_to(fa_icon('check-square-o', text: 'View all'), bookings_path) %>
        <table class='table table-striped bookings_history margin_up'>
          <thead>
            <tr>
              <th>Customer Name</th>
              <th>Treatment</th>
              <th>Date / Time</th>
            </tr>
          </thead>
          <tbody>
            <% @bookings.each do |booking| %>
              <tr>
                <td>
                  <%= "#{booking.consumer.first_name} " "#{booking.consumer.last_name}" %>
                </td>
                <td><%= booking.treatment.title %></td>
                <td><%= booking.start_at.strftime("%B %d at %H:%M") %></td>
              </tr>
            <%end%>
          </tbody>
        </table>
      </div>

      <div class="col-sm-12 col-md-12 button_down">
        <div class="col-sm-6 col-md-6">
          <%= column_chart current_user.historical_financies, label: 'earned pounds' %>
        </div>
        <div class="col-sm-6 col-md-6">
          <h5>Popular treatments</h5>
          <table class='table margin_up'>
            <tbody>
              <% current_user.popular_treatments.each do |treatment| %>
                <tr>
                  <td>
                    <%= treatment.title %>
                  </td>
                  <td><%= fa_icon('gbp', text:"#{current_user.treatment_this_month(treatment.id)}") %></td>
                </tr>
              <%end%>
            </tbody>
          </table>      
        </div>      
      </div>
    </div>
  </div>
</div>