config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'venues#index'

  devise_for :consumers, controllers: { registrations: 'consumers/registrations', omniauth_callbacks: 'omniauth_callbacks', invitations: 'users/invitations' }

  resources :venues, only: [:show, :update, :index, :create]
  resources :transactions, only: [:new, :create, :index]
  resources :bookings, only: [:new] do
    post :confirm, on: :collection
  end
  resource :cart, only: [:show]
  resource :balance, only: [:create] do
    get :show, as: :gifts
  end
  resources :reviews, only: [:new, :create, :index]
  resources :vouchers, only: [:update] do
    get :add_gift, on: :collection
  end
  get 'gift_card', to: 'vouchers#buy_gift_card', as: :buy_gift_card

  scope '/pro' do
    devise_for :pros, controllers: { invitations: 'users/invitations' }

    resources :pros
    resources :treatments do
      post :select_featured, on: :collection
    end
    resources :treatment_groups
    resources :daily_schedules, only: [:index, :destroy] do
      post :set, on: :collection
    end

    resources :teams, only: [:create, :show] do
      post :add_member, on: :member
      get :check_for_team, on: :collection
    end
    resources :bookings, only: [:create, :index, :destroy] do
      get :calendar, on: :collection
      post :mark_as_unavailable, on: :collection
      post :complete, on: :member
    end
    resources :venues, only: [:edit, :new]
    resources :bank_accounts, only: [:update, :edit, :new, :create]
    resource :dashboard, only: [:show]
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  before_action :check_cart!, only: [:new]

  def index
    @bookings = Booking.where(consumer: current_user, confirmed: true).order(:paid)
  end

  def new
    allowance = Bookings::CheckAllowance.new(params)
    redirect_to :back, notice: allowance.notice and return unless allowance.call

    set_gift_info if buying_gift?
    update_total if paying_with_gift?
    gon.client_token = generate_client_token
    @cart_total = @gift || cart_total
  end

  def create
    base = Transactions::Creator.new(params, current_user)
    transaction = base.call
    render :new, notice: 'Something went wrong. Please try again!' and return unless transaction.success?

    notice = base.notice

    if !params[:balance_payment].blank?
      redirect_to root_url, notice: "Your transaction has been successful! New balance £ #{current_user.balance.amount.to_i}. #{notice}"
    elsif !params[:gift].blank?
      redirect_to gifts_balance_url, notice: 'You bought a gift!'
    else
      redirect_to root_url, notice: "Congratulations! Your transaction has been successfully processed! #{notice}"
    end
  end

  private

  def buying_gift?
    params[:gift] && params[:gift][:amount]
  end

  def paying_with_gift?
    params[:gifts_amount] && params[:total]
  end

  def set_gift_info
    quantity = params[:gift][:quantity].to_i
    amount = params[:gift][:amount].to_i
    @gift = quantity ? amount * quantity : amount
  end

  def update_total
    @gift = params[:total].to_i - params[:gifts_amount].to_i
  end

  def cart_ids
    ShoppingCart.new(current_user).cart_ids
  end

  def cart_total
    Booking.find(cart_ids).sum(&:sum)
  end

  def check_cart!
    if Booking.find(cart_ids).blank? && !params[:gift][:amount]
      redirect_to root_url, alert: 'Please add some items to your cart before processing your transaction!'
    end
  end

  def generate_client_token
    if current_user.has_payment_info?
      Braintree::ClientToken.generate(customer_id: current_user.braintree_customer_id)
    else
      Braintree::ClientToken.generate
    end
  end
end

app/views/transactions/_customer_form.html.erb
<h4>Please enter your personal info:</h4>
<div class='form-group'>
  <%= text_field_tag :first_name, "",placeholder: "First Name", class: 'form-control' %>
</div>
<div class='form-group'>
  <%= text_field_tag :last_name, "",placeholder: "Last Name", class: 'form-control' %>
</div>
<div class='form-group last_div'>
  <%= text_field_tag :phone, "",placeholder: "Phone", class: 'form-control' %>
</div>

app/views/transactions/index.html.erb
<div class='container'>

  <div class='row' >
    <div class='col-md-10 margin_up' >

    <h3>Bookings history</h3>

    <table class='table table-striped bookings_history margin_up'>
      <thead>
        <tr>
          <th>Venue</th>
          <th>Treatment</th>
          <th>Start at</th>
          <th>Payment made</th>
          <th>Sum</th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |booking| %>
          <tr>
            <td>
              <%= booking.pro.try(:venue).try(:name) %><br />
              <%= link_to 'leave a review', new_review_path(booking: booking) %>
            </td>
            <td><%= booking.treatment.title %></td>
            <td><%= booking.start_at.strftime("%B %d at %H:%M") %></td>
            <td><%= "paid at #{booking.updated_at}" if booking.paid %></td>
            <td><span><%= fa_icon('gbp', text:"#{booking.sum}") %></span></td>
          </tr>
        <%end%>
      </tbody>
    </table>

    </div>
  </div>

</div>

app/views/transactions/new.html.erb
<div class='form-group'>
  <h2 class='text-center last_div'>New Transaction</h2>
  <div class='col-lg-6 col-lg-offset-3'>
    <%= form_tag transactions_path do%>
      <%= hidden_field_tag :gift, "#{@gift}" %>
      <% if params[:gift] %>
        <%= hidden_field_tag :message, "#{params[:gift][:message]}" %>
        <%= hidden_field_tag :email, "#{params[:gift][:email]}" %>
        <%= hidden_field_tag :quantity, "#{params[:gift][:quantity]}" %>
      <% end %>  
      <%= hidden_field_tag :balance_payment, "#{params[:gifts_amount]}" %>

      <%= render 'customer_form' unless current_user.has_payment_info? %>
      <h4>Please enter your payment details:</h4>
      <div id='dropin'></div>
      <button class='btn btn-primary' style='width:400px;'>
        <span class='pay-button'>Pay  </span><span><%= fa_icon('gbp', text:"#{@cart_total}") %></span>
      </button>
    <%end%>
  </div>
</div>